### PR TITLE
Allow switching the socket class

### LINKED ISSUE #413: Add support for Celluloid::IO sockets
Bunny does not currently expose a mechanism to inject a custom socket class through it's API.
In order to cooperate with Celluloid::IO's reactor we either need that API or to provide support for it by checking if `Celluloid::IO.evented?` is equal to true.
What do you think?

### PR DESCRIPTION
**Pull request by thedrow**
This is another attempt to fix #413.
It's not clear what we should do about SSLSocket though since Celluloid provides an implementation for it as well. Any ideas?

Also this doesn't have a test just yet but it will.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you. We can either do the same for TLS sockets or switch to supporting specifically Celluloid which will then be used in both places. The latter is OK (I doubt we will have many alternative socket implementations) but the former won't tie us to Celluloid.

**Comment by thedrow** [comment]
Bunny's SSLSocket inherits from OpenSSL's SSLSocket which doesn't allow me to replace the implementation of the socket.

**Comment by michaelklishin** [comment]
@thedrow we can refactor that part and extract an "interface." I'm open to suggestions :) We can make `Bunny::Transport` pluggable and with a base class, too, allowing you to implement any socket implementation logic you please. Note that this will have more significant ramifications for automated testing.

**Comment by michaelklishin** [comment]
No activity on this one and looks like TLS is not covered by this => closing.

**Pull request closed without merging**
