### PR TITLE
Verify peer by default

### PR DESCRIPTION
**Pull request by michaelklishin**
@foeken

### CODE REVIEW

**Comment by foeken** [comment]
:+1: I think this is a great solution.

**Comment by carlhoerberg** [comment]
If the test server's cert is generated from `./spec/tls/cacert.pem` then there's no need to disable `verify_peer` in the tests. If the test server's cert isn't generated from `./spec/tls/cacert.pem` then why bother supplying it? Also I'm in heavy favor of having `verify_peer` on, "secure-by-default". Developers already have the same "problem" with `Net::HTTP` et. al.

**Comment by michaelklishin** [comment]
@carlhoerberg host names do not match. The tests are connecting to localhost but that's not what certificates use.

**Comment by carlhoerberg** [comment]
Ok, then why not generate one that has CN=localhost?

**Comment by michaelklishin** [comment]
@carlhoerberg some day :)

**Comment by carlhoerberg** [comment]
```
openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout localhost-key.pem -out localhost-cert.pem -subj "/CN=localhost" -days 3650
```

**Comment by michaelklishin** [comment]
We use tls-gen ;)

**Pull request merged**
