### PR TITLE
0.7.x: support boolean headers

### PR DESCRIPTION
**Pull request by maxlaverse**
According to the specifications, it should be possible to provide boolean values for a header.
Currently the `Buffer.write` method does not support this types and lead to invalid packets.

This PR adds support for writing boolean header, and fixes the reading to return a boolean value.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you but I honestly don't know how I feel about doing a `0.7.x` release. What prevents you from upgrading?

**Comment by skaes** [comment]
@michaelklishin we're running 50+ applications on this version, via our beetle gem. Upgrading would be quite some effort for us, and we have more important items on our roadmap.

I was planning to merge this pull request and release the new gem version, but you were quicker.

**Comment by michaelklishin** [comment]
@skaes understood. Feel free to produce a release :) Will Beetle always use Bunny 0.7.x?

**Comment by skaes** [comment]
@michaelklishin I don't think we'll always the old version. If we find the time, we might switch. But the new version is a big rewrite, so we have to be careful.

**Comment by michaelklishin** [comment]
@skaes Bunny 0.9 was pretty compatible with 0.7.x but I understand what you mean. Bunny 0.7.x is the only AMQP 0-8 client I see used, though.

**Pull request merged**
